app/users/forms.py
from flask_wtf import FlaskForm, RecaptchaField
from flask_wtf.file import FileField, FileAllowed
from wtforms import StringField, PasswordField, SubmitField, BooleanField, RadioField, IntegerField, SelectField
from wtforms.fields.html5 import DateField
from wtforms.validators import DataRequired, Length, Email, EqualTo, ValidationError
from flask_login import current_user




class UpdateAccountForm(FlaskForm):
    username = StringField('Username',
                           validators=[DataRequired(), Length(min=2, max=20)])
    email = StringField('Email',
                        validators=[DataRequired(), Email()])
    about_me = StringField('About you', validators=[DataRequired()])
    web_url = StringField('website URL')
    gender = RadioField('Gender', choices = [('Male','Male'),('Female','Female')], validators=[DataRequired()])
    contact_number = IntegerField("phone number", validators=[DataRequired()])
    date_of_birth = DateField('date of birth', format="%Y-%m-%d")
    picture = FileField('Update Profile Picture', validators=[FileAllowed(['jpg', 'png'])])
    submit = SubmitField('Update')

    def validate_username(self, username):
        if username.data != User.username:
            user = User.query.filter_by(username=username.data).first()
            if user:
                raise ValidationError('That username is taken. Please choose a different one.')

    def validate_username(self, email):
        if email.data != User.email:
            user = User.query.filter_by(email=email.data).first()
            if user:
                raise ValidationError('That email is taken. Please choose a different one.')





class LinksForm(FlaskForm):
    facebook_id = StringField('link Facebook')
    twitter_id = StringField('Link Twitter')
    instagram_id = StringField(' Link Instagram ')
    snapchat_id = StringField(' Link Snapchat ')
    submit = SubmitField('Update')

class IntrestForm(FlaskForm):
    intrest_type = StringField('Intrest name')
    submit = SubmitField('Update')



class EventsForm(FlaskForm):
    event_name = StringField('Event Name')
    event_description = StringField('Event description')
    event_location = StringField('location')
    event_start_date = DateField(' Start Date', format="%Y-%m-%d")
    event_end_date = DateField(' End Date', format="%Y-%m-%d")
    event_status = BooleanField('Event Status')
    submit = SubmitField('Update')



class MediaForm(FlaskForm):
    image = FileField('Upload Picture', validators=[FileAllowed(['jpg', 'png'])])
    media_format = SelectField('Media type ', choices = [('image', 'image')])
    submit = SubmitField('upload')

app/users/__init__.py
from flask import Blueprint

bp = Blueprint('users', __name__)

from . import routes

app/users/routes.py
from flask import render_template, url_for, flash, redirect, request, g
from flask_login import login_user, current_user, logout_user, login_required
from app import db, bcrypt
from datetime import datetime
from app.users import bp
from app.models import (User, Post, Follow, Role, Permission, 
                         PostLike, CommentLike, BlogLike, BlogCommentLike)
from app.users.forms import ( UpdateAccountForm,  EventsForm,  
                                 LinksForm,  MediaForm, )
from app.users.utils import save_picture
from app.main.forms import SearchForm


@bp.before_request
def before_request():
    if current_user.is_authenticated:
        current_user.last_seen = datetime.utcnow()
        g.search_form = SearchForm()
        db.session.commit()



@bp.route("/account/<int:id>", methods=['GET', 'POST'])
@login_required
def account(id):
    form = UpdateAccountForm()
    user = User.query.get_or_404(id)
    if form.validate_on_submit():
        if form.picture.data:
            picture_file = save_picture(form.picture.data)
            user.image_file = picture_file
        user.last_name = form.last_name.data
        user.first_name = form.first_name.data
        user.username = form.username.data
        user.email = form.email.data
        user.about_me= form.about_me.data
        user.gender = form.gender.data
        user.web_url = form.web_url.data
        user.contact_number = form.contact_number.data
        user.date_of_birth = form.date_of_birth.data
        db.session.commit()
        flash('Your account has been updated!', 'success')
        return redirect(url_for('users.user', id=user.id))
    elif request.method == 'GET':
        form.first_name.data = user.first_name
        form.last_name.data = user.last_name
        form.username.data = user.username
        form.email.data = user.email
        form.about_me.data = user.about_me
        form.gender.data = user.gender
        form.web_url.data = user.web_url
        form.contact_number.data = user.contact_number
        form.date_of_birth.data = user.date_of_birth
    image_file = url_for('static', filename='profile_pics/' + user
        .image_file)
    return render_template('users/account.html', title='Account',
                           image_file=image_file, form=form, user=user)





@bp.route("/user/<int:id>", methods=['GET', 'POST'])
def user(id):
    page = request.args.get('page', 1, type=int)
    user = User.query.filter_by(id=id).first_or_404()
    datetimecurr = datetime.utcnow()
    user_id = user.id
    links = Links.query.filter_by(user_id=id).first()
    image_file = url_for('static', filename='profile_pics/' + user.image_file)
    posts = Post.query.filter_by(Protagonist=user)\
        .order_by(Post.date_posted.desc())\
        .paginate(page=page, per_page=5)
    return render_template('users/user.html', datetimecurr=datetimecurr, image_file=image_file, posts=posts, user=user,  links=links)






@bp.route('/follow/<int:id>')
@login_required
def follow(id):
    user = User.query.filter_by(id=id).first()
    if user is None:
        flash(('User not found','warning'))
        return redirect(url_for('main.home'))
    if current_user.is_following(user):
        flash('You are already following this user', 'warning')
        return redirect(url_for('main.home', id=id))
    if user == current_user:
        flash(('You cannot follow yourself!', 'warning'))
        return redirect(url_for('main.home', id=id))
    current_user.follow(user)
    db.session.commit()
    flash('You are now following this user' , 'success' )
    return redirect(url_for('users.user', id=id))




@bp.route('/unfollow/<int:id>')
@login_required
def unfollow(id):
    user = User.query.filter_by(id=id).first()
    if user is None:
        flash(('User  not found.', 'warning'))
        return redirect(url_for('main.home'))
    if user == current_user:
        flash(('You cannot unfollow yourself!', 'warning'))
        return redirect(url_for('users.home', id=id))
    current_user.unfollow(user)
    db.session.commit()
    flash('You are not following this user anymore', 'danger'  )
    return redirect(url_for('users.user', id=id))

@bp.route('/followers/<int:id>')
def followers(id):
    user = User.query.filter_by(id=username).first()
    if user is None:
        flash('Invalid user', 'warning')
        return redirect(url_for('users.user'))
    page = request.args.get('page', 1, type=int)
    pagination = user.followers.paginate(
        page, per_page=current_app.config['FLASKY_FOLLOWERS_PER_PAGE'],
        error_out=False)
    follows = [{'user': item.follower, 'timestamp': item.timestamp}
               for item in pagination.items]
    return render_template('users/followers.html', user=user, title="Followers of",
                           endpoint='followers', pagination=pagination,
                           follows=follows)


@bp.route('/followed_by/<int:id>')
def followed_by(id):
    user = User.query.filter_by(id=id).first()
    if user is None:
        flash('Invalid user.')
        return redirect(url_for('users.user'))
    page = request.args.get('page', 1, type=int)
    pagination = user.followed.paginate(
        page, per_page=current_app.config['FLASKY_FOLLOWERS_PER_PAGE'],
        error_out=False)
    follows = [{'user': item.followed, 'timestamp': item.timestamp}
               for item in pagination.items]
    return render_template('followers.html', user=user, title="Followed by",
                           endpoint='followed_by', pagination=pagination,
                           follows=follows)

app/templates/users/account.html
{% extends "layout.html" %}
{% block content %}
    <div class="content-section">
      <div class="media">
        <img class="rounded-circle account-img" src="{{ image_file }}">
        <div class="media-body">
          <h2 class="account-heading">{{ user.username }}</h2>
          <p class="text-secondary">{{ user.email }}</p>
        </div>
      </div>


        <form method="POST" action="" enctype="multipart/form-data">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Account Info</legend>
                 <button class="btn btn-outline-info btn-sm m-1" type="button" name="button"><a href="{{ url_for('users.address',id=user.id) }}">{{ ('Address') }}</a>
       </button>
      <button class="btn btn-outline-info btn-sm m-1" type="button" name="button"><a href="{{ url_for('users.occupation',id=user.id) }}">{{ ('Occumpation') }}</a>
       </button>
        <button class="btn btn-outline-info btn-sm m-1" type="button" name="button"><a href="{{ url_for('users.links',id=user.id) }}">{{ ('Social Links') }}</a>
       </button>
       <button class="btn btn-outline-info btn-sm m-1" type="button" name="button"><a href="{{ url_for('users.intrest',id=user.id) }}">{{ ('Interest') }}</a>
        </button>
         <button class="btn btn-outline-info btn-sm m-1" type="button" name="button"><a href="{{ url_for('users.achievement',id=user.id) }}">{{ ('Achievement') }}</a>
        </button>
        <button class="btn btn-outline-info btn-sm m-1" type="button" name="button"><a href="{{ url_for('users.special_event',id=user.id) }}">{{ ('Special Moments') }}</a>
        </button>
        <button class="btn btn-outline-info btn-sm m-1" type="button" name="button"><a href="{{ url_for('users.language',id=user.id) }}">{{ ('Language') }}</a>
        </button>
         <button class="btn btn-outline-info btn-sm m-1" type="button" name="button"><a href="{{ url_for('users.sponsership',id=user.id) }}">{{ ('sponsership') }}</a>
        </button>
        {% if user.category == 'Sports' %}
        <button class="btn btn-outline-info btn-sm m-1" type="button" name="button"><a href="{{ url_for('users.sports',id=user.id) }}">{{ ('sports carrier') }}</a>
       </button>
       {% endif %}
         <br>
         <br>   <div class="form-group">
             {{ form.first_name.label(class="form-control-label") }}
             {% if form.first_name.errors %}
                 {{ form.first_name(class="form-control form-control-lg is-invalid") }}
                 <div class="invalid-feedback">
                     {% for error in form.first_name.errors %}
                         <span>{{ error }}</span>
                     {% endfor %}
                 </div>
             {% else %}
                 {{ form.first_name(class="form-control form-control-lg") }}
             {% endif %}
         </div>
         <div class="form-group">
             {{ form.last_name.label(class="form-control-label") }}
             {% if form.last_name.errors %}
                 {{ form.last_name(class="form-control form-control-lg is-invalid") }}
                 <div class="invalid-feedback">
                     {% for error in form.last_name.errors %}
                         <span>{{ error }}</span>
                     {% endfor %}
                 </div>
             {% else %}
                 {{ form.last_name(class="form-control form-control-lg") }}
             {% endif %}
         </div>
                <div class="form-group">
                    {{ form.about_me.label(class="form-control-label") }}
                    {% if form.about_me.errors %}
                        {{ form.about_me(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.about_me.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.about_me(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.web_url.label(class="form-control-label") }}
                    {% if form.web_url.errors %}
                        {{ form.web_url(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.web_url.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.web_url(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.username.label(class="form-control-label") }}

                    {% if form.username.errors %}
                        {{ form.username(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.username.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}date_of_birth
                        </div>
                    {% else %}
                        {{ form.username(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.gender.label(class="form-control-label") }}

                    {% if form.gender.errors %}
                        {{ form.gender(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.gender.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.gender(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.date_of_birth.label(class="form-control-label") }}

                    {% if form.date_of_birth.errors %}
                        {{ form.date_of_birth(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.date_of_birth.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.date_of_birth(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.contact_number.label(class="form-control-label") }}

                    {% if form.contact_number.errors %}
                        {{ form.contact_number(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.contact_number.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.contact_number(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.education_level.label(class="form-control-label") }}

                    {% if form.education_level.errors %}
                        {{ form.education_level(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.education_level.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.education_institution(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.education_institution.label(class="form-control-label") }}

                    {% if form.education_institution.errors %}
                        {{ form.education_institution(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.education_institution.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.education_institution(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.email.label(class="form-control-label") }}
                    {% if form.email.errors %}
                        {{ form.email(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.email(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.picture.label() }}
                    {{ form.picture(class="form-control-file") }}
                    {% if form.picture.errors %}
                        {% for error in form.picture.errors %}
                            <span class="text-danger">{{ error }}</span><br>
                        {% endfor %}
                    {% endif %}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
            </div>
        </form>
    </div>
{% endblock content %}

app/templates/users/links.html
{% extends "layout.html" %}
{% block content %}
<div class="content-section">
    <form method="POST" action="">
        {{ form.hidden_tag() }}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">{{ legend }}</legend>



            <!--Repeat this code block for additional item you want to show  -->
            <div class="form-group">
                {{ form.facebook_id.label(class="form-control-label") }}
                {% if form.facebook_id.errors %}
                    {{ form.facebook_id(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.facebook_id.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.facebook_id(class="form-control form-control-lg") }}
                {% endif %}
            </div>
            <!--Insert here your items in div element for all the data you need  -->

            <!--Repeat this code block for additional item you want to show  -->
            <div class="form-group">
                {{ form.twitter_id.label(class="form-control-label") }}
                {% if form.twitter_id.errors %}
                    {{ form.twitter_id(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.twitter_id.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.twitter_id(class="form-control form-control-lg") }}
                {% endif %}
            </div>
            <!--Insert here your items in div element for all the data you need  -->

            <!--Repeat this code block for additional item you want to show  -->
            <div class="form-group">
                {{ form.instagram_id.label(class="form-control-label") }}
                {% if form.instagram_id.errors %}
                    {{ form.instagram_id(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.instagram_id.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.instagram_id(class="form-control form-control-lg") }}
                {% endif %}
            </div>
            <!--Insert here your items in div element for all the data you need  -->

            <!--Repeat this code block for additional item you want to show  -->

            <!--Insert here your items in div element for all the data you need  -->


            <!--Repeat this code block for additional item you want to show  -->

            <div class="form-group">
                {{ form.snapchat_id.label(class="form-control-label") }}
                {% if form.snapchat_id.errors %}
                    {{ form.snapchat_id(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.snapchat_id.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.snapchat_id(class="form-control form-control-lg") }}
                {% endif %}
            </div>





        </fieldset>
        <div class="form-group">
            {{ form.submit(class="btn btn-outline-info") }}
        </div>
    </form>
</div>
{% endblock content %}

app/templates/users/user.html
{% extends "layout.html" %}
{% block content %}
<div class="container m-top">
  <div class="p-3 shadow">
<div class="d-inline-flex">
  <div>
  <img class="mx-auto d-block" src="{{ url_for('static', filename='wall.jpg') }}">
  <img class="rounded-circle img" alt="5 Terre" src="{{ image_file }}">
</div>
<div class="ml-3 mt-4">
  <h1>{{ user.username }}</h1>
  <p>Active {{ moment(user.last_seen).fromNow() }}</p>
</div>
</div>
<p class="ml-lg-4 ml-0"><b> Followers: <span class="badge">{{ user.followers.count() -1 }}</span></b>
<b> Following: <span class="badge">{{ user.followed.count() -1 }}</span></b>
{% if current_user.is_authenticated and user != current_user and user.is_following(current_user) %}
<span class="label label-default">Follows you</span>
{% endif %}</p>
<p class="ml-lg-4 ml-0">{{ user.about_me}}</p>
  <nav class="navbar navbar-expand-sm bg-dark navbar-dark bgbar">

    <ul class="navbar-nav">
      {% if user != current_user %}
      <li class="nav-item active">
        <a class="nav-item nav-link" title="send message" href="{{ url_for('messages.send_message', id=user.id) }}"><i
            class="far fa-comments"></i>&#xA0;Chat </a>

        {% if not current_user.is_following(user) %}
      <li class="nav-item active">
        <a class="nav-item nav-link" title="follow" href="{{ url_for('users.follow', id=user.id) }}"><i class="fas fa-user-plus"></i>&#xA0;Follow</a>
      </li>
      {% else %}
      <li class="nav-item active">
        <a class="nav-item nav-link" title="Unfollow" href="{{ url_for('users.unfollow', id=user.id) }}"><i class="fas fa-user-minus"></i>&#xA0;UnFollow</a>
      </li>
      {% endif %}
      {% endif %}
      </li>
      {% if user == current_user %}
      <li class="nav-item active">
        <a class="nav-item nav-link" title="edit profile" href="{{ url_for('users.account',id=user.id) }}"><i class="fas fa-pencil-alt"></i>&#xA0;Edit
          Profile</a>
      </li>
      <li class="nav-item active">
        <a class="nav-item nav-link" title="Uplod Pictures " href="{{ url_for('users.media',id=user.id) }}"><i class="far fa-images"></i>&#xA0;Add
          Pictures</a>
      </li>
      <li class="nav-item active">
        <a class="nav-item nav-link" title="Events" href="{{ url_for('users.events',id=user.id) }}"><i class="far fa-calendar-alt"></i>&#xA0;Events</a>
      </li>
      <li class="nav-item active">
        <a class="nav-item nav-link" title="Create Post" href="{{ url_for('posts.new_post',id=user.id) }}"><i class="fas fa-comment-alt"></i>&#xA0;New
          Post</a>
      </li>
      <li class="nav-item active">
        <a class="nav-item nav-link" title="New Blog" href="{{ url_for('blog.new_blog', id=current_user.id) }}"><i
            class="fas fa-passport"></i>&#xA0;New
          blog </a>
      </li>

      <li class="nav-item active">
        <a class="nav-item nav-link" title="more information" data-toggle="modal" href="#" data-target="#myModal"><i
            class="fas fa-caret-down"></i>&#xA0;More</a>
      </li>
      {% endif %}
    </ul>
  </nav>
  {% if current_user.is_administrator() %}
  <nav class="navbar navbar-expand-sm bg-danger navbar-dark bgbar">

    <ul class="navbar-nav">
      <li class="nav-item active">
        <a class="nav-item nav-link" title="edit profile" href="{{ url_for('users.account',id=user.id) }}"><i class="fas fa-pencil-alt"></i>&#xA0;Edit
          Profile</a>
      </li>
      <li class="nav-item active">
        <a class="nav-item nav-link" title="Uplod Pictures " href="{{ url_for('users.media',id=user.id) }}"><i class="far fa-images"></i>&#xA0;Add
          Pictures</a>
      </li>
      <li class="nav-item active">
        <a class="nav-item nav-link" title="Travel" href="{{ url_for('users.travel',id=user.id) }}"><i class="fas fa-plane-departure"></i>&#xA0;Travel</a>
      </li>
      <li class="nav-item active">
        <a class="nav-item nav-link" title="Events" href="{{ url_for('users.events',id=user.id) }}"><i class="far fa-calendar-alt"></i>&#xA0;Events</a>
      </li>
      <li class="nav-item active">
        <a class="nav-item nav-link" title="Create Post" href="{{ url_for('posts.new_post',id=user.id) }}"><i class="fas fa-comment-alt"></i>&#xA0;New
          Post</a>
      </li>
      <li class="nav-item active">
        <a class="nav-item nav-link" title="New Blog" href="{{ url_for('blog.new_blog', id=current_user.id) }}"><i
            class="fas fa-passport"></i>&#xA0;New
          blog </a>
      </li>
      <li class="nav-item active">
        <a class="nav-item nav-link" title="more information" data-toggle="modal" href="#" data-target="#myModal"><i
            class="fas fa-caret-down"></i>&#xA0;More</a>
      </li>


    </ul>
  </nav>
  {% endif %}





  <div id="social">
    <a class="facebookBtn smGlobalBtn" href="https://www.facebook.com/{{links_facebook_id}}"></a>
    <a class="twitterBtn smGlobalBtn" href="https://twitter.com/{{links.twitter_id}}"></a>
    <a class="instagramBtn smGlobalBtn" href="http://www.instagram.com/{{links.instagram_id}}"></a>
    <a class="snapchatBtn smGlobalBtn" href="https://www.snapchat.com/add/{{links.snapchat_id}}"></a>
  </div>
  <div class="modal" id="myModal">
    <div class="modal-dialog">
      <div class="modal-content">

        <!-- Modal Header -->
        <div class="modal-header">
          <h4 class="modal-title">Background</h4>
          <button type="button" class="close" data-dismiss="modal">&times;</button>
        </div>
        <!-- Modal body -->
        <div class="modal-body">

          <div class="formd">
            <b>
              <h4 class="text-dark">Basic</h4>
            </b>
            <b class="text-muted mr-2">First Name</b>{{user.first_name}}<br>
            <b class="text-muted mr-2">Last Name</b>{{user.last_name}}<br>
            <b class="text-muted mr-2">Email</b>{{user.username}}<br>
            <b class="text-muted mr-2">Email</b>{{user.email}}<br>
            <p><b class="text-muted mr-2">Member since</b>{{
              moment(user.member_since).format('L') }}<br>
              <b class="text-muted mr-2">Born</b>{{ moment(user.date_of_birth).format('L') }}<br>
              <b class="text-muted mr-2">Gender</b>{{user.gender}}<br>
              <b class="text-muted mr-2">Phone Number</b>{{user.contact_number}}<br>
          </div>
        </div>

        <!-- Modal footer -->
        <div class="modal-footer">
          <button type="button" class="btn btn-danger" data-dismiss="modal">Close</button>
        </div>

      </div>
    </div>
  </div>

  {% for post in posts.items %}
  <img class="rounded-circle article-img" src="{{ url_for('static', filename='profile_pics/' + post.Protagonist.image_file) }}">
  {% if post.category=='Sports' %}
  <h1><i class="fas fa-basketball-ball"></i></h1>
  {% endif %}
  {% if post.category=='Design' %}
  <h1><i class="fas fa-palette"></i></h1>
  {% endif %}
  {% if post.category=='Travel' %}
  <h1><i class="fas fa-umbrella-beach"></i></h1>
  {% endif %}
  {% if post.category=='Peoples Corner' %}
  <h1><i class="fas fa-person-booth"></i></h1>
  {% endif %}
  {% if post.category=='Music' %}
  <h1><i class="fas fa-podcast"></i></h1>
  {% endif %}
  {% if post.category=='Others' %}
  <h1><i class="fas fa-project-diagram"></i></h1>
  {% endif %}
  {% if current_user.is_authenticated %}
  <h2><a class="text-primary" href="{{ url_for('users.user', id=post.Protagonist.id) }}">{{
      post.Protagonist.username }}</a></h2>
  {% else %}
  <h2>{{ post.Protagonist.username }}</h2>
  {% endif %}

  <small class="text-muted"> {{
    moment(post.date_posted).fromNow() }}</small>

  <button class="btn btn-link">
    <a href="http://maps.google.com/?q={{post.city }}">
      <i style="color: black;" class="fas fa-map-marker-alt"></i>&#xA0;{{post.city }}
    </a>
  </button>

  <div>
    <h2>{{post.category}}</h2>
  </div>
  <div>
    <h4><a a href=" {{ url_for('posts.postn', post_id=post.id) }}">{{post.story_line }}</a></h4>
  </div>
  <div>
    <iframe class="
        iframe" scrolling="yes" src="https://www.youtube.com/embed/{{post.youtube_link.split("=")[1]}}"
      frameborder="0" allowfullscreen></iframe>
  </div>

  <div>
    <p id="content" class="text-secondary" scrolling="yes"><b>My Story</b> <br> <br>
      {{post.story_text }}
    </p>
    <a href="{{ url_for('posts.postn', post_id=post.id) }}"><b>Read more</b></a>
  </div>
</div>

<div>
  <a href="{{ url_for('posts.postn', post_id=post.id) }}#comments">
    <span class="label label-primary">{{ post.comments.count() }} Comments</span></a>
</div>
</div>
</article>

{% endfor %}
{% for page_num in posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
{% if page_num %}
{% if posts.page == page_num %}
<a class="btn btn-info mb-4" href="{{ url_for('users.user', id=user.id, page=page_num) }}">{{ page_num }}</a>
{% else %}
<a class="btn btn-outline-info mb-4" href="{{ url_for('users.user', id=user.id, page=page_num) }}">{{ page_num }}</a>
{% endif %}
{% else %}
...
{% endif %}
{% endfor %}
</div>
</div>
</div>

{% endblock content %}