app/blog/forms.py
from flask_wtf.file import FileField, FileAllowed
from flask_wtf import FlaskForm
from wtforms import StringField, TextAreaField, PasswordField, SubmitField, BooleanField, RadioField, IntegerField, SelectField
from wtforms.fields.html5 import DateField
from wtforms.validators import DataRequired
from app.models import User, Comment
from flask_ckeditor import CKEditorField


class BlogForm(FlaskForm):
    city = StringField('City', validators=[DataRequired()])
    category = SelectField('Choose your blog subject', choices=[('Analytics', 'Analytics'), ('Web-Devlopment', 'Web Devlopment'),
                                                                ('Cloud', 'Cloud'), ('Automation', 'Automation'),  ('Mobile-Applications', 'Mobile Applications'), ('Data-Visualization', 'Data Visualization'), ('Process-Optimization', 'Process Optimization'), ('Security', 'Security'), ('Audit', 'Audit'), ('Pharma', 'Pharma'), ('Agriculture', 'Agriculture'), ('Blockchain', 'Blockchain'), ('IOT', 'Internt of things')])
    title = StringField('Blog Headline', validators=[DataRequired()])
    summary = TextAreaField('Short description ', validators=[DataRequired()])
    story = CKEditorField('Blog Text', validators=[DataRequired()])
    picture = FileField('Upload pictures', validators=[FileAllowed(['jpg', 'png'])])

    submit = SubmitField('Post')

class BlogCommentForm(FlaskForm):
    body = StringField('Enter your comment', validators=[DataRequired()])

    submit = SubmitField('Submit')

app/blog/__init__.py
from flask import Blueprint

bp = Blueprint('blog', __name__)

from . import routes

app/blog/routes.py
from flask import (render_template, url_for, flash, current_app, request, g,
                   redirect, request, abort,current_app, make_response)
from flask_login import current_user, login_required
from flask_sqlalchemy import get_debug_queries
from app import db
from app.blog import bp
from app.models import Blog, User, BlogComment, BlogLike, BlogCommentLike
from app.blog.forms import BlogForm, BlogCommentForm
from app.blog.utils import save_picture
from datetime import datetime
from app.main.forms import SearchForm

@bp.before_request
def before_request():
    if current_user.is_authenticated:
        current_user.last_seen = datetime.utcnow()
        g.search_form = SearchForm()
        db.session.commit()


@bp.route("/blogview")
def blog_view():
    page = request.args.get('page', 1, type=int)
    blogs = Blog.query.order_by(Blog.timestamp.desc()).paginate(page=page, per_page=100)
    return render_template('blog/blogview.html', blogs=blogs, current_time=datetime.utcnow(), title="Blogs")


@bp.route("/blog/<int:id>", methods=['GET', 'POST'])
@login_required
def new_blog(id):
    form = BlogForm()
    user = User.query.get_or_404(id)
    if form.validate_on_submit():
        picture_file = save_picture(form.picture.data)
        blog = Blog(city=form.city.data,
                    image_file=picture_file,
                    category=form.category.data,
                    summary=form.summary.data,
                    title=form.title.data,
                    story=form.story.data,
                    blog_author= user)
        db.session.add(blog)
        db.session.commit()
        flash('Your blog post has been created', 'success')
        return redirect(url_for('blog.blog_view'))
    return render_template('blog/create_blog.html', title='New Blog',
                           form=form, legend='New Blog')


@bp.route("/blogn/<int:blog_id>",  methods=['GET', 'POST'])
def blogn(blog_id):
    blog = Blog.query.get_or_404(blog_id)
    blogcomment=BlogComment
    form = BlogCommentForm()
    if form.validate_on_submit():
        blogcomment = BlogComment(body=form.body.data,
                          blog=blog,
                          blog_author=current_user._get_current_object() )
        db.session.add(blogcomment)
        db.session.commit()
        flash('Your blog comment has been published.', 'success')
        return redirect(url_for('blog.blogn', blog_id=blog.id, page=-1))
    page = request.args.get('page', 1, type=int)
    if page == -1:
        page = (blog.blogcomments.count() - 1) // \
            current_app.config['FLASKY_COMMENTS_PER_PAGE'] + 1
    pages = request.args.get('page', 1, type=int)
    blogsx = Blog.query.order_by(
        Blog.timestamp.desc()).paginate(page=pages, per_page=7)
    

    return render_template('blog/blog.html', blogs=[blog],blog=blog, form=form, blogsx=blogsx,
                           blogcomment=blogcomment, title=blog.title)


@bp.route("/blog/<int:blog_id>/update", methods=['GET', 'POST'])
@login_required
def update_blog(blog_id):
    blog = Blog.query.get_or_404(blog_id)
    form = BlogForm()
    if form.validate_on_submit():
        if form.picture.data:
            picture_file = save_picture(form.picture.data)
            blog.image_file = picture_file
        blog.city = form.city.data
        blog.category = form.category.data
        blog.title = form.title.data
        blog.summary = form.summary.data
        blog.story = form.story.data
        db.session.commit()
        flash(' Blog post has been updated!', 'success')
        return redirect(url_for('blog.blogn', blog_id=blog.id))
    elif request.method == 'GET':
        form.city.data = blog.city
        form.category.data = blog.category
        form.title.data = blog.title
        form.summary.data = blog.summary
        form.story.data = blog.story
    return render_template('blog/create_blog.html', title='Update Blog',
                           form=form, legend='Update Blog')


@bp.route("/blog/<int:blog_id>/delete", methods=['POST'])
@login_required

def delete_blog(blog_id):
    blog = Blog.query.get_or_404(blog_id)
    db.session.delete(blog)
    db.session.commit()
    flash('Blog post has been deleted!', 'success')
    return redirect(url_for('blog.blog_view'))

@bp.route('/bloglike/<int:blog_id>/<action>')
@login_required
def bloglike_action(blog_id, action):
    blog = Blog.query.filter_by(id=blog_id).first_or_404()
    if action == 'like':
        current_user.like_blog(blog)
        db.session.commit()
    if action == 'unlike':
        current_user.unlike_blog(blog)
        db.session.commit()
    return redirect(url_for('blog.blogn', blog_id=blog.id, page=-1))

@bp.route('/blogcommentlike/<int:blog_comment_id>/<action>')
@login_required
def blogcommentlike_action(blog_comment_id, action):
    blogcomment = BlogComment.query.filter_by(id=blog_comment_id).first_or_404()
    if action == 'like':
        current_user.like_blogcomment(blogcomment)
        db.session.commit()
    if action == 'unlike':
        current_user.unlike_blogcomment(blogcomment)
        db.session.commit()
    return redirect(url_for('blog.blog_view'))

app/templates/blog/blog.html
{% extends "layout.html" %}
<head>
{% block head %}
<meta property="og:title" content="{{ blog.title }}">
<meta property="og:description" content="{{ blog.summary }}">
<meta property="og:type" content="article" />
<meta property="og:image" content="{{ url_for('static', filename='blog_pics/' + blog.image_file) }}">
<meta name="twitter:card" content="{{ url_for('static', filename='blog_pics/' + blog.image_file) }}">
<meta name="twitter:title" content="{{ blog.title }}">
<meta name="twitter:description" content="{{ blog.summary }}">

{{ super() }}
{% endblock head %}
</head>
{% block content %}
<style>
.padding-0{
    padding-right:0;
    padding-left:0;
}
.icon-bar {
    position: fixed;
        top: 25%;
        left: 0;
        list-style: none;
        padding-left: 0;
        z-index: 10;
        margin: 0;
        -webkit-transition: right 0.25s ease-in-out;
        transition: right 0.25s ease-in-out;
        display: -webkit-box;
        display: -ms-flexbox;
        display: flex;
        -webkit-box-orient: vertical;
        -webkit-box-direction: normal;
        -ms-flex-direction: column;
        flex-direction: column;
  }
.icon-bar a {
    display: block;
    text-align: center;
    padding: 16px;
    transition: all 0.3s ease;
    color: white;
    font-size: 20px;
  }
  
  .icon-bar a:hover {
    -webkit-transform: scale(1.5);
    -ms-transform: scale(1.5);
    -moz-transform: scale(1.5);
    transform: scale(1.5);
  }
  
  .facebook {
    background: #3B5998;
    color: white;
  }
  
  .twitter {
    background: #55ACEE;
    color: white;
  }
  
  .google {
    background: #dd4b39;
    color: white;
  }
  
  .linkedin {
    background: #007bb5;
    color: white;
  }
  
  .youtube {
    background: #bb0000;
    color: white;
  }
  .mobileview {
        display: none;
    }
    .mobileviewdisplay {
        display: block;
    }
    .float-none {
    width: auto;
}
  
</style>

<div class="section-empty section-item">
        <div id="socialbar" class="icon-bar" style="display:none;">
                <a target="_blank" href="#" data-social="share-facebook" data-toggle="tooltip"
                                data-placement="top" title="Facebook">
                                <i class="fa fa-facebook text-s circle"></i>
                            </a>
                            <a target="_blank" href="#" data-social="share-twitter" data-toggle="tooltip"
                                data-placement="top" title="Twitter">
                                <i class="fa fa-twitter text-s circle"></i>
                            </a>
                            <a target="_blank" href="#" data-social="share-google" data-toggle="tooltip"
                                data-placement="top" title="Google+">
                                <i class="fa fa-google-plus text-s circle"></i>
                            </a>
                            <a target="_blank" href="#" data-social="share-linkedin" data-toggle="tooltip"
                                data-placement="top" title="LinkedIn">
                                <i class="fa fa-linkedin text-s circle"></i>
                            </a>
              </div>
    <div class="container content">
        <div class="row">
            <div class="col-md-8 col-sm-12">
                    <div id="iconMobile" class="mobileview">

                       
                            <div class="btn-group social-group btn-group-icons">
                                <a target="_blank" href="#" data-social="share-facebook" data-toggle="tooltip"
                                    data-placement="top" title="Facebook">
                                    <i class="fa fa-facebook text-s circle"></i>
                                </a>
                                <a target="_blank" href="#" data-social="share-twitter" data-toggle="tooltip"
                                    data-placement="top" title="Twitter">
                                    <i class="fa fa-twitter text-s circle"></i>
                                </a>
                                <a target="_blank" href="#" data-social="share-google" data-toggle="tooltip"
                                    data-placement="top" title="Google+">
                                    <i class="fa fa-google-plus text-s circle"></i>
                                </a>
                                <a target="_blank" href="#" data-social="share-linkedin" data-toggle="tooltip"
                                    data-placement="top" title="LinkedIn">
                                    <i class="fa fa-linkedin text-s circle"></i>
                                </a>
                            </div>
                        </div>
                {% if blog.blog_author == current_user%}
                <span><form action="{{ url_for('blog.delete_blog', blog_id=blog.id) }}" method="POST">
<input class="btn btn-info" type="submit" value="Delete">
</form></span>
{% endif %}
                <h4 class="text-xl">{{ blog.title }}</h4>
                <hr class="space xs" />
                <div class="tag-row">
                    <span class="col-xs-12 col-lg-3  float-none padding-0"><i class="fa fa-calendar"></i> <a href="#">{{ moment(blog.timestamp).format('Do MMMM YYYY') }}</a></span>
                    <span class="col-xs-12 col-lg-3 float-none padding-0"><i class="fa fa-bookmark"></i> <a href="#">{{ blog.category }}</a></span>
                    <span class="col-xs-12 col-lg-3  float-none padding-0"><i class="fa fa-pencil"></i><a href="#">{{ blog.blog_author.username }}</a></span>
                    {% if blog.blog_author == current_user%}
                    <span class="col-xs-12 col-lg-1 float-none padding-0" style="border-right:none !important; "><i class="fa fa-edit"></i><a href="{{ url_for('blog.update_blog', blog_id=blog.id) }}">Edit</a></span>
                   {% endif %}
                    
                    
                </div>
                <hr class="space" />
                <a class="img-box lightbox i-left" href="{{ url_for('static', filename='blog_pics/' + blog.image_file) }}" data-lightbox-anima="fade-bottom">
                    
                    <img src="{{ url_for('static', filename='blog_pics/' + blog.image_file) }}" alt="">
                </a>
                <hr class="space" />
                <div >
                    <div style="color: black !important;" class="panel">
                        <p>
                            {{blog.story|safe}}
                        </p>
                        <div class="section-empty section-doc">
                            <div class="container content" style="font-size:14px !important;">
                        
                                <div style="background:#eeeeee;border:1px solid #cccccc;padding:5px 10px; font-size: 12px !important;">*Use
                                    Cases and
                                    Community features are coming Soon! Please stay tuned for more future updates.&nbsp;</div>
                        
                            </div>
                        </div>
                    </div>
                    
                </div>
                <hr class="space visible-sm" />
            </div>
            <div class="col-md-4 col-sm-12 boxed-inverse shadow-1">
                
                <hr class="space m" />
                
                <div class="list-group latest-post-list list-blog">
                    <p class="list-group-item active">Latest posts</p>
                     {% for blogx in blogsx.items %}
                    <div class="list-group-item">
                        <div class="row">
                            <div class="tag-row icon-row"><span><i class="fa fa-calendar"></i>{{ moment(blogx.timestamp).format('DD MMM YYYY') }}</span></div>
                      <a href="#">
                          <h5><a href="{{ url_for('blog.blogn', blog_id=blogx.id) }}">{{blogx.title }}</a></h5>
                      </a>
                      <p>
                          {{blogx.summary }}
                      </p>
                        </div>
                    </div>
                    {% endfor %}
                </div>
               
                <hr class="space m" />
                
            </div>
        </div>
    </div>
</div>
<i class="scroll-top scroll-top-mobile show fa fa-sort-asc"></i>
<link rel="stylesheet" href="{{ url_for('static', filename='HTWF/scripts/font-awesome/css/font-awesome.css') }}">
        <script async src="{{ url_for('static', filename='HTWF/scripts/bootstrap/js/bootstrap.min.js') }}"></script>
        <script src="{{ url_for('static', filename='HTWF/scripts/imagesloaded.min.js') }}"></script>
        <script src="{{ url_for('static', filename='HTWF/scripts/jquery.tab-accordion.js') }}"></script>
        <script src="{{ url_for('static', filename='HTWF/scripts/smooth.scroll.min.js') }}"></script>
        <script async src="{{ url_for('static', filename='HTWF/scripts/jquery.magnific-popup.min.js') }}"></script>
        <script>
                var alterClass = function () {
                    var ww = document.body.clientWidth;
                    if (ww < 780) {
                        $('#iconMobile').removeClass('mobileview');
                        $('#iconMobile').addClass('mobileviewdisplay');
            
                    } else if (ww >= 781) {
            
                        $('#iconMobile').addClass('mobileview');
                        $('#iconMobile').removeClass('mobileviewdisplay');
            
            
                    };
                };
                $(window).resize(function () {
                    alterClass();
                });
                //Fire it when the page first loads:
                alterClass();
                $(document).scroll(function () {
                    if ($(window).width() > 950) {
                    var a = $(document).scrollTop() + window.innerHeight;
                    var y = $(this).scrollTop();
                    var b = $('#footer').offset().top;
                    if ((y > 500) && (a < b)) {
                        $('.icon-bar').fadeIn();
                        $('#socialbar').css('bottom', '10px');
                    } else {
                        $('.icon-bar').fadeOut();
                        $('#socialbar').css('bottom', (10 + (a - b)) + 'px');
                    }
                        // var footerpos = $('#footer').offset().top;
                        // var y = $(this).scrollTop();
                        // var x = $(this).scroll();
                        // if ((y > 500) && (x < footerpos)) {
                        //     $('.icon-bar').fadeIn();
                        // } else {
                        //     $('.icon-bar').fadeOut();
                        // }
                    }
                });
            </script>
{% endblock content %}

app/templates/blog/blogview.html
{% extends "layout.html" %}
<head>
  {% block head %}
  <meta property="og:image" content="{{ url_for('static', filename='images/wall.png') }}">
  <meta name="twitter:card" content="{{ url_for('static', filename='images/wall.png') }}">

  {{ super() }}
  {% endblock head %}
</head>
{% block content %}



<div class="header-title" style="background-image:url('{{ url_for('static', filename='images/bg-img-3.png') }}')">
  <div class="container">
    <div class="title-base">
      <hr class="anima" />
      <h1>Quantamix blogs</h1>
      <p>Latest news from our blog and our social channels</p>
    </div>
  </div>
</div>

<div class="section-empty section-item">
  <div class="container content">
    <div class="row">
      <div class="col-md-8 col-center col-sm-12">
        <div class="grid-list one-row-list">
          <div class="grid-box row">
            {% for blog in blogs.items %}
            <div class="grid-item col-md-12">
              <div class="advs-box niche-box-blog">
                <div class="block-top">
                  <div class="block-infos">
                    <div class="block-data">
                      <p class="bd-day">{{ moment(blog.timestamp).format('DD') }}</p>
                      <p class="bd-month">{{ moment(blog.timestamp).format('MMM') }}</p>
                    </div>
                    <a class="block-comment" href="#">2 <i class="fa fa-comment-o"></i></a>
                  </div>
                  <div class="block-title">
                    <h3><a href="{{ url_for('blog.blogn', blog_id=blog.id) }}">{{blog.title }}</a></h3>
                    <div class="tag-row">
                      <span><i class="fa fa-bookmark"></i> <a href="#">{{blog.category }}</a></span>
                      <span><i class="fa fa-pencil"></i><a>{{blog.blog_author.username }}</a></span>
                      <span><i class="fa fa-map-marker"></i><a href="http://maps.google.com/?q={{blog.city }}">{{blog.city }}</a></span>
                    </div>
                  </div>
                </div>
                <a class="img-box" href="{{ url_for('blog.blogn', blog_id=blog.id) }}">
                  <img src="{{ url_for('static', filename='blog_pics/' + blog.image_file) }}"
                    alt="">
                </a>
                <p class="excerpt" >
                  {{blog.summary }}
                </p>
              </div>
              <hr class="space m" />
            </div>
            {% endfor %}
          </div>
          <!-- <div class="list-nav">
            <ul class="pagination pagination-grid hide-first-last pagination-sm" data-page-items="3"
              data-pagination-anima="show-scale" data-options="scrollTop:true"></ul>
          </div> -->
        </div>
      </div>

    </div>
  </div>
</div>
<link rel="stylesheet" href="{{ url_for('static', filename='HTWF/scripts/font-awesome/css/font-awesome.css') }}">
<script async src="{{ url_for('static', filename='HTWF/scripts/bootstrap/js/bootstrap.min.js') }}"></script>
<script src="{{ url_for('static', filename='HTWF/scripts/imagesloaded.min.js') }}"></script>
<script src="{{ url_for('static', filename='HTWF/scripts/jquery.twbsPagination.min.js') }}"></script>
<script src="{{ url_for('static', filename='HTWF/scripts/jquery.magnific-popup.min.js') }}"></script>
<script src="{{ url_for('static', filename='HTWF/scripts/parallax.min.js') }}"></script>
<script src="{{ url_for('static', filename='HTWF/scripts/smooth.scroll.min.js') }}"></script>
{% endblock content %}

app/templates/blog/create_blog.html
{% extends "layout.html" %}
{% block content %}
<div class="container m-top">
    <div class="p-4 shadow my-2">
        <form method="POST" action="" enctype="multipart/form-data">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">{{ legend }}</legend>
                <!--Repeat this code block for additional item you want to show  -->
                <div class="form-group">
                    {{ form.city.label(class="form-control-label") }}
                    {% if form.city.errors %}
                    {{ form.city(class="form-control is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.city.errors %}
                        <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                    {% else %}
                    {{ form.city(class="form-control", id="googleplaces") }}
                    {% endif %}
                </div>
                <!--Insert here your items in div element for all the data you need  -->

                <!--Repeat this code block for additional item you want to show  -->
                <div class="form-group">
                    {{ form.category.label(class="form-control-label") }}
                    {% if form.category.errors %}
                    {{ form.category(class="form-control is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.category.errors %}
                        <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                    {% else %}
                    {{ form.category(class="form-control") }}
                    {% endif %}
                </div>
                <!--Insert here your items in div element for all the data you need  -->

                <!--Repeat this code block for additional item you want to show  -->
                <div class="form-group">
                    {{ form.title.label(class="form-control-label") }}
                    {% if form.title.errors %}
                    {{ form.title(class="form-control is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.title.errors %}
                        <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                    {% else %}
                    {{ form.title(class="form-control") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.summary.label(class="form-control-label") }}
                    {% if form.summary.errors %}
                    {{ form.summary(class="form-control is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.summary.errors %}
                        <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                    {% else %}
                    {{ form.summary(class="form-control") }}
                    {% endif %}
                </div>

                <div class="form-group">
                    {{ form.story.label(class="form-control-label") }}
                    {% if form.story.errors %}
                    {{ form.story(class="form-control is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.story.errors %}
                        <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                    {% else %}
                    {{ form.story(class="form-control") }}
                    {% endif %}
                </div>
                <!--Insert here your items in div element for all the data you need  -->
                <!--Repeat this code block for additional item you want to show  -->
            <div class="form-group">
                {{ form.picture.label(class="form-control-label pt-1", style="font-size:20px;") }}
                {{ form.picture(class="form-control-file", style="font-size:20px;") }}
            
                {% if form.picture.errors %}
                {% for error in form.picture.errors %}
                <span class="text-danger">{{ error }}</span><br>
                {% endfor %}
                {% endif %}
            </div>
                <!--Insert here your items in div element for all the data you need  -->


                <!--PLACEHOLDERS to add more data fields      -->





            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
            </div>
        </form>
    </div>
    <script>
        function activatePlacesSearch() {
            var input = document.getElementById('googleplaces');
            var autocomplete = new google.maps.places.Autocomplete(input);
        }
    </script>
    
    <script type="text/javascript"
        src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCZZjkOg4_d2Fw6BBN6UeDDqkh-PqgSzDU&libraries=places&callback=activatePlacesSearch"></script>
</div>
{% endblock content %}