app/platform/forms.py
from flask_wtf import FlaskForm
from flask_wtf.file import FileField, FileAllowed
from wtforms import StringField, SubmitField, TextAreaField, SelectField
from wtforms.validators import DataRequired
from app.models import User, Comment
from flask_ckeditor import CKEditorField


class PlatformForm(FlaskForm):
    city = StringField('City', validators=[DataRequired()])
    category = SelectField('Category', choices=[('Analytics', 'Analytics'), ('Web-Devlopment', 'Web Devlopment'),
                                                ('Cloud', 'Cloud'), ('Automation', 'Automation'),  ('Mobile-Applications', 'Mobile Applications'), ('Data-Visualization', 'Data Visualization'), ('Process-Optimization', 'Process Optimization'), ('Security', 'Security'), ('Audit', 'Audit'), ('Pharma', 'Pharma'), ('Agriculture', 'Agriculture'), ('Blockchain', 'Blockchain'), ('IOT', 'Internt of things')])
    title = StringField('Platform Headline', validators=[DataRequired()])
    summary = TextAreaField('Short description ', validators=[DataRequired()])
    description = CKEditorField('Platform Text', validators=[DataRequired()])
    picture = FileField('Upload pictures', validators=[FileAllowed(['jpg', 'png'])])
    submit = SubmitField('Post')

class CommentForm(FlaskForm):
    body = StringField('Enter your comment', validators=[DataRequired()])
    submit = SubmitField('Submit')

app/platform/__init__.py
from flask import Blueprint

bp = Blueprint('platform', __name__)

from . import routes

app/platform/routes.py
from flask import (render_template, url_for, flash, request, g,
                   redirect, request, abort, current_app, make_response)
from flask_login import current_user, login_required
from flask_sqlalchemy import get_debug_queries
from app import db
from datetime import datetime
from app.platform import bp
from app.models import Platform, User, PlatformComment, PlatformLike, PlatformCommentLike
from app.platform.forms import PlatformForm, CommentForm
from app.platform.utils import save_picture
from app.main.forms import SearchForm

@bp.before_request
def before_request():
    if current_user.is_authenticated:
        current_user.last_seen = datetime.utcnow()
        g.search_form = SearchForm()
        db.session.commit()


@bp.route("/platform/<int:id>", methods=['GET', 'POST'])
@login_required
def new_platform(id):
    form = PlatformForm()
    user = User.query.get_or_404(id)
    if form.validate_on_submit():
        picture_file = save_picture(form.picture.data)
        platform = Platform(city=form.city.data,
                    image_file=picture_file,
                    category=form.category.data,
                    summary=form.summary.data,
                    title=form.title.data,
                    description=form.description.data,
                    Protagonist= user)
        db.session.add(platform)
        db.session.commit()
        flash('Your Platform post has been created!', 'success')
        return redirect(url_for('main.platform'))
    return render_template('platform/create_platform.html', title='New Post',
                           form=form, legend='Create Solution')


@bp.route("/platformn/<int:platform_id>",  methods=['GET', 'POST'])
def platformn(platform_id):
    platform = Platform.query.get_or_404(platform_id)
    platformcomment = PlatformComment
    form = CommentForm()
    if form.validate_on_submit():
        comment = PlatformComment(body=form.body.data,
                          platform=platform,
                          Protagonist=current_user._get_current_object() )
        db.session.add(comment)
        db.session.commit()
        flash('Your comment has been published.', 'success')
        return redirect(request.referrer)
    page = request.args.get('page', 1, type=int)
    if page == -1:
        page = (platform.comments.count() - 1) // \
            current_app.config['FLASKY_COMMENTS_PER_PAGE'] + 1
    pagination = platform.comments.order_by(PlatformComment.timestamp.asc()).paginate(
        page, per_page=current_app.config['FLASKY_COMMENTS_PER_PAGE'],
        error_out=False)
    comments = pagination.items

    return render_template('platform/platform.html',  platforms=[platform], platform=platform, form=form,
                              comments=comments, pagination=pagination, platformcomment=platformcomment, title=platform.title)


@bp.route("/platform/<int:platform_id>/update", methods=['GET', 'POST'])
@login_required
def update_platform(platform_id):
    platform = Platform.query.get_or_404(platform_id)
    form = PlatformForm()
    if form.validate_on_submit():
        if form.picture.data:
            picture_file = save_picture(form.picture.data)
            platform.image_file = picture_file
        platform.city = form.city.data
        platform.category = form.category.data
        platform.summary = form.summary.data
        platform.title = form.title.data
        platform.description = form.description.data
        db.session.commit()
        flash(' post has been updated!', 'success')
        return redirect(url_for('platform.platformn', platform_id=platform.id))
    elif request.method == 'GET':
        form.city.data = platform.city
        form.category.data = platform.category
        form.summary.data = platform.summary
        form.title.data = platform.title
        form.description.data = platform.description
    return render_template('platform/create_platform.html', title='Update',
                           form=form, legend='Update Platform Post')


@bp.route("/platform/<int:platform_id>/delete", methods=['POST'])
@login_required
def delete_platform(platform_id):
    platform = Platform.query.get_or_404(platform_id)
    db.session.delete(platform)
    db.session.commit()
    flash( 'post has been deleted!', 'success')
    return redirect(request.referrer)

app/templates/platform/create_platform.html
{% extends "layout.html" %}
{% block content %}
<div class="container m-top">
    <div class="p-4 shadow my-2">
        <form method="POST" action="" enctype="multipart/form-data">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">{{ legend }}</legend>
                <!--Repeat this code block for additional item you want to show  -->
                <div class="form-group">
                    {{ form.city.label(class="form-control-label") }}
                    {% if form.city.errors %}
                    {{ form.city(class="form-control is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.city.errors %}
                        <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                    {% else %}
                    {{ form.city(class="form-control", id="googleplaces") }}
                    {% endif %}
                </div>
                <!--Insert here your items in div element for all the data you need  -->

                <!--Repeat this code block for additional item you want to show  -->
                <div class="form-group">
                    {{ form.category.label(class="form-control-label") }}
                    {% if form.category.errors %}
                    {{ form.category(class="form-control is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.category.errors %}
                        <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                    {% else %}
                    {{ form.category(class="form-control") }}
                    {% endif %}
                </div>
                <!--Insert here your items in div element for all the data you need  -->

                <!--Repeat this code block for additional item you want to show  -->
                <div class="form-group">
                    {{ form.title.label(class="form-control-label") }}
                    {% if form.title.errors %}
                    {{ form.title(class="form-control is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.title.errors %}
                        <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                    {% else %}
                    {{ form.title(class="form-control") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.summary.label(class="form-control-label") }}
                    {% if form.summary.errors %}
                    {{ form.summary(class="form-control is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.summary.errors %}
                        <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                    {% else %}
                    {{ form.summary(class="form-control") }}
                    {% endif %}
                </div>

                <div class="form-group">
                    {{ form.description.label(class="form-control-label") }}
                    {% if form.description.errors %}
                    {{ form.description(class="form-control is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.description.errors %}
                        <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                    {% else %}
                    {{ form.description(class="form-control") }}
                    {% endif %}
                </div>
                <!--Insert here your items in div element for all the data you need  -->
                <!--Repeat this code block for additional item you want to show  -->
                <div class="form-group">
                    {{ form.picture.label(class="form-control-label pt-1", style="font-size:20px;") }}
                    {{ form.picture(class="form-control-file", style="font-size:20px;") }}

                    {% if form.picture.errors %}
                    {% for error in form.picture.errors %}
                    <span class="text-danger">{{ error }}</span><br>
                    {% endfor %}
                    {% endif %}
                </div>
                <!--Insert here your items in div element for all the data you need  -->


                <!--PLACEHOLDERS to add more data fields      -->





            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
            </div>
        </form>
    </div>
    <script>
        function activatePlacesSearch() {
            var input = document.getElementById('googleplaces');
            var autocomplete = new google.maps.places.Autocomplete(input);
        }
    </script>

    <script type="text/javascript"
        src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCZZjkOg4_d2Fw6BBN6UeDDqkh-PqgSzDU&libraries=places&callback=activatePlacesSearch"></script>
</div>
{% endblock content %}

app/templates/platform/platform.html
{% extends "layout.html" %}
<head>
        {% block head %}
        <meta property="og:title" content="{{ platform.title }}">
        <meta property="og:description" content="{{ platform.summary }}">
        <meta property="og:type" content="article" />
        <meta property="og:image" content="{{ url_for('static', filename='platform_pics/' + platform.image_file) }}">
        <meta name="twitter:card" content="{{ url_for('static', filename='platform_pics/' + platform.image_file) }}">
        <meta name="twitter:title" content="{{ platform.title }}">
        <meta name="twitter:description" content="{{ platform.summary }}">
        
        {{ super() }}
        {% endblock head %}
        </head>
{% block content %}

<style>
    p {
        color: black;
        max-width: 740px;
        margin-left: auto;
        margin-right: auto;
    }

    h3 {
        color: black;
        white-space: normal;
    }
    ul{
        text-align:justify;
        padding:0;
        margin:0;
    }
    .padding-0 {
        padding-right: 0;
        padding-left: 0;
    }
 
.icon-bar {
    position: fixed;
        top: 25%;
        left: 10%;
        list-style: none;
        padding-left: 0;
        z-index: 10;
        margin: 0;
        -webkit-transition: right 0.25s ease-in-out;
        transition: right 0.25s ease-in-out;
        display: -webkit-box;
        display: -ms-flexbox;
        display: flex;
        -webkit-box-orient: vertical;
        -webkit-box-direction: normal;
        -ms-flex-direction: column;
        flex-direction: column;
  }
  
  .icon-bar a {
    display: block;
    text-align: center;
    padding: 16px;
    transition: all 0.3s ease;
    color: white;
    font-size: 20px;
  }
  
  .icon-bar a:hover {
    -webkit-transform: scale(1.5);
    -ms-transform: scale(1.5);
    -moz-transform: scale(1.5);
    transform: scale(1.5);
  }
  
  .facebook {
    background: #3B5998;
    color: white;
  }
  
  .twitter {
    background: #55ACEE;
    color: white;
  }
  
  .google {
    background: #dd4b39;
    color: white;
  }
  
  .linkedin {
    background: #007bb5;
    color: white;
  }
  
  .youtube {
    background: #bb0000;
    color: white;
  }
  
  .content {
    margin-left: 75px;
    font-size: 30px;
  }
  .mobileview {
        display: none;
    }

    .mobileviewdisplay {
        display: block;
    }
   
    @media (max-width: 994px){
        h1 {
        font-size: 2.8em;
        line-height: 28px;
        white-space:normal;
        font-weight:normal;
       }
       #socialbar{
           display:none;
       }
    }
   

    /* .backgroundOverlay::before{
    -webkit-filter:progid:DXImageTransform.Microsoft.gradient( startColorstr='#002c8a', endColorstr='#000d72ff',GradientType=1 );
    filter: progid:DXImageTransform.Microsoft.gradient( startColorstr='#002c8a', endColorstr='#000d72ff',GradientType=1 );
} */
</style>

<div class="header-title white ken-burn-center img-box adv-img adv-img-classic-box" data-parallax="scroll"
    data-position="top" data-natural-height="950" data-natural-width="1920"
    data-image-src="{{ url_for('static', filename='platform_pics/' + platform.image_file) }}" style=" ">
    <div class="caption">
            <div class="caption-inner">
                <h1>{{ platform.title }}</h1>
                <br>
                <p class="big-text">{{ platform.summary }} </p>
            </div>
        </div>
</div>


<div class="section-empty">
        <div id="socialbar" class="icon-bar" style="display:none;">
                <a target="_blank" href="#" data-social="share-facebook" data-toggle="tooltip"
                                data-placement="top" title="Facebook">
                                <i class="fa fa-facebook text-s circle"></i>
                            </a>
                            <a target="_blank" href="#" data-social="share-twitter" data-toggle="tooltip"
                                data-placement="top" title="Twitter">
                                <i class="fa fa-twitter text-s circle"></i>
                            </a>
                            <a target="_blank" href="#" data-social="share-google" data-toggle="tooltip"
                                data-placement="top" title="Google+">
                                <i class="fa fa-google-plus text-s circle"></i>
                            </a>
                            <a target="_blank" href="#" data-social="share-linkedin" data-toggle="tooltip"
                                data-placement="top" title="LinkedIn">
                                <i class="fa fa-linkedin text-s circle"></i>
                            </a>
              </div>
    <div class="container content" style="padding-top: 50px;max-width: 800px;margin-left: auto;margin-right: auto;">
        <div class="row vertical-row">
              
            <div class="col-md-12 col-sm-12">
                    <div id="iconMobile" class="mobileview">

                       
                            <div class="btn-group social-group btn-group-icons">
                                <a target="_blank" href="#" data-social="share-facebook" data-toggle="tooltip"
                                    data-placement="top" title="Facebook">
                                    <i class="fa fa-facebook text-s circle"></i>
                                </a>
                                <a target="_blank" href="#" data-social="share-twitter" data-toggle="tooltip"
                                    data-placement="top" title="Twitter">
                                    <i class="fa fa-twitter text-s circle"></i>
                                </a>
                                <a target="_blank" href="#" data-social="share-google" data-toggle="tooltip"
                                    data-placement="top" title="Google+">
                                    <i class="fa fa-google-plus text-s circle"></i>
                                </a>
                                <a target="_blank" href="#" data-social="share-linkedin" data-toggle="tooltip"
                                    data-placement="top" title="LinkedIn">
                                    <i class="fa fa-linkedin text-s circle"></i>
                                </a>
                            </div>
                        </div>
                {% if platform.Protagonist == current_user%}
                <span>
                    <form action="{{ url_for('platform.delete_platform', platform_id=platform.id) }}" method="POST">
                        <input class="btn btn-info" type="submit" value="Delete">
                    </form>
                </span>
                {% endif %}
                <br>
                {% if platform.Protagonist == current_user%}
                <div class="tag-row">
                    <span class="col-xs-12 col-lg-2  padding-0" style="font-size:0.4em;"><i class="fa fa-calendar"></i> <a
                            href="#">{{ moment(platform.timestamp).format('Do MMMM YYYY') }}</a></span>
                    <span class="col-xs-12 col-lg-2  padding-0" style="font-size:0.4em;"><i class="fa fa-bookmark"></i> <a
                            href="#">{{ platform.category }}</a></span>
                    <span class="col-xs-12 col-lg-3  padding-0" style="font-size:0.4em;"><i class="fa fa-pencil ml-2"></i><a
                            href="#">{{ platform.Protagonist.username }}</a></span>
                    <span class="col-xs-12 col-lg-3  padding-0" style="font-size:0.4em;"><i class="fa fa-map-marker"></i><a
                            href="http://maps.google.com/?q={{platform.city }}">{{ platform.city }}</a></span>
                    {% if platform.Protagonist == current_user%}
                    <span class="col-xs-12 col-lg-1  padding-0" style="border-right:none !important;font-size:0.4em;"><i
                            class="fa fa-edit"></i><a
                            href="{{ url_for('platform.update_platform', platform_id=platform.id) }}">Edit</a></span>
                    {% endif %}


                </div>
                {% endif %}
                <br>
                <br>
                <p style="color:#0e1a35 !important;">
                    {{platform.description|safe}}
                </p>
                <div class="section-empty section-doc">
                    <div class="container content">
                
                        <div style="background:#eeeeee;border:1px solid #cccccc;padding:5px 10px;  font-size: 12px !important;">*Use Cases and Community features are
                            coming Soon! Please stay tuned for more future updates.&nbsp;</div>
                
                    </div>
                </div>
                <hr class="space m" />
                <div class="row">
                   
                    <div class="col-md-6">

                        <hr class="space m" />

                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="section-empty"></div>

</div>
<i class="scroll-top scroll-top-mobile show fa fa-sort-asc"></i>
<script src="{{ url_for('static', filename='HTWF/scripts/parallax.min.js') }}"></script>
<link rel="stylesheet" href="{{ url_for('static', filename='HTWF/scripts/font-awesome/css/font-awesome.css') }}">
<script async src="{{ url_for('static', filename='HTWF/scripts/bootstrap/js/bootstrap.min.js') }}"></script>
<script src="{{ url_for('static', filename='HTWF/scripts/imagesloaded.min.js') }}"></script>
<script src="{{ url_for('static', filename='HTWF/scripts/flexslider/jquery.flexslider-min.js') }}"></script>
<script src="{{ url_for('static', filename='HTWF/scripts/jquery.magnific-popup.min.js') }}"></script>
<script src="{{ url_for('static', filename='HTWF/scripts/jquery.tab-accordion.js') }}"></script>
<script src="{{ url_for('static', filename='HTWF/scripts/bootstrap/js/bootstrap.popover.min.js') }}"></script>
<script src="{{ url_for('static', filename='HTWF/scripts/smooth.scroll.min.js') }}"></script>
<script>
        var alterClass = function () {
            var ww = document.body.clientWidth;
            if (ww < 780) {
                $('#iconMobile').removeClass('mobileview');
                $('#iconMobile').addClass('mobileviewdisplay');
    
            } else if (ww >= 781) {
    
                $('#iconMobile').addClass('mobileview');
                $('#iconMobile').removeClass('mobileviewdisplay');
    
    
            };
        };
        $(window).resize(function () {
            alterClass();
        });
        //Fire it when the page first loads:
        alterClass();
        $(document).scroll(function () {
            if ($(window).width() > 950) {
            var a = $(document).scrollTop() + window.innerHeight;
            var y = $(this).scrollTop();
            var b = $('#footer').offset().top;
            if ((y > 500) && (a < b)) {
                $('.icon-bar').fadeIn();
                $('#socialbar').css('bottom', '10px');
            } else {
                $('.icon-bar').fadeOut();
                $('#socialbar').css('bottom', (10 + (a - b)) + 'px');
            }
                // var footerpos = $('#footer').offset().top;
                // var y = $(this).scrollTop();
                // var x = $(this).scroll();
                // if ((y > 500) && (x < footerpos)) {
                //     $('.icon-bar').fadeIn();
                // } else {
                //     $('.icon-bar').fadeOut();
                // }
            }
        });
    </script>
{% endblock content %}